# Copyright (C) 2012  Internet Systems Consortium, Inc. ("ISC")
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS.  IN NO EVENT SHALL ISC BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
# OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

# No namespace declaration - these constants go in the global namespace
# of the config_messages python module.

# since these messages are for the python server_common library, care must
# be taken that names do not conflict with the messages from the c++
# server_common library. A checker script should verify that, but we do not
# have that at this moment. So when adding a message, make sure that
# the name is not already used in src/lib/config/config_messages.mes

% PYSERVER_COMMON_AUTH_CONFIG_NAME_PARSER_ERROR Invalid name when parsing Auth configuration: %1
There was an invalid name when parsing Auth configuration.

% PYSERVER_COMMON_AUTH_CONFIG_RRCLASS_ERROR Invalid RRClass when parsing Auth configuration: %1
There was an invalid RR class when parsing Auth configuration.

% PYSERVER_COMMON_DNS_TCP_SEND_DONE completed sending TCP message to %1 (%2 bytes in total)
Debug message.  A complete DNS message has been successfully
transmitted over a TCP connection, possibly after multiple send
operations.  The destination address and the total size of the message
(including the 2-byte length field) are shown in the log message.

% PYSERVER_COMMON_DNS_TCP_SEND_ERROR failed to send TCP message to %1 (%2/%3 bytes sent): %4
A DNS message has been attempted to be sent out over a TCP connection,
but it failed due to some network error.  Although it's not expected
to happen too often, it can still happen for various reasons.  The
administrator may want to examine the cause of the failure, which is
included in the log message, to see if it requires some action to
be taken at the server side.  When this message is logged, the
corresponding  TCP connection was closed immediately after the error
was detected.

% PYSERVER_COMMON_DNS_TCP_SEND_PENDING sent part TCP message to %1 (up to %2/%3 bytes)
Debug message.  A part of DNS message has been transmitted over a TCP
connection, and it's suspended because further attempt would block.
The destination address and the total size of the message that has
been transmitted so far (including the 2-byte length field) are shown
in the log message.

% PYSERVER_COMMON_TSIG_KEYRING_DEINIT Deinitializing global TSIG keyring
A debug message noting that the global TSIG keyring is being removed from
memory. Most programs don't do that, they just exit, which is OK.

% PYSERVER_COMMON_TSIG_KEYRING_INIT Initializing global TSIG keyring
A debug message noting the TSIG keyring storage is being prepared. It should
appear at most once in the lifetime of a program. The keyring still needs
to be loaded from configuration.

% PYSERVER_COMMON_TSIG_KEYRING_UPDATE Updating global TSIG keyring
A debug message. The TSIG keyring is being (re)loaded from configuration.
This happens at startup or when the configuration changes. The old keyring
is removed and new one created with all the keys.
